### ISSUE TITLE
ObservableReadonly creation from Observable

### ISSUE THREAD

**Issue by andreichuk** [fabiospampinato/voby#2]
How is it supposed to create `ObservableReadonly<T>` from `Observable<T>`? Is there anything similar to `$.readonly(someObservable)` utility from **oby** lib? I saw `ObservableAbstract<T, Ti>` type has `readonly` prop but its return type is `ObservableReadonlyAbstract<T, TI>`, not  `ObservableReadonly<T>`.

**Comment by fabiospampinato** [comment]
>  I saw ObservableAbstract<T, Ti> type has readonly prop but its return type is ObservableReadonlyAbstract<T, TI>, not ObservableReadonly<T>.

That should be the same type at the end of the day, basically you can just call `foo.readonly ()`.

--- 

Oby kind of got rewritten with v6, now I need to update Voby to use that. 

- With the current version of Voby, given an observable: you can just call `foo.readonly ()` to make a readonly version of it.
- With the future version of Voby, given an observable and a new `readonly` function: you would instead call `readonly ( foo )`. I haven't decided yet if it should be named `readonly` or `useReadonly` though, do you have a preference?

Also Oby's `readonly` function is just a computed that calls the observable, potentially you could just copy/paste this function in your project and use it already https://github.com/fabiospampinato/oby/blob/c0a6b32e87988c06c93d1cb88ab061127263a6a2/src/methods/readonly.ts#L9-L17

I've also simplified the types a lot in oby@v6, so ObservableAbstract, ObservableReadonlyAbstract, and all the methods attached to observables just got deleted.

Does this address the question?

**Comment by andreichuk** [comment]
> Also Oby's readonly function is just a computed that calls the observable, potentially you could just copy/paste this function in your project and use it already https://github.com/fabiospampinato/oby/blob/c0a6b32e87988c06c93d1cb88ab061127263a6a2/src/methods/readonly.ts#L9-L17

I use `const observableReadonly = useComputed(() => observable);` for now.

> With the future version of Voby, given an observable and a new readonly function: you would instead call readonly ( foo ). I haven't decided yet if it should be named readonly or useReadonly though, do you have a preference?

No preference.
I wonder whether it can done in the following way: `interface ObservableReadonly<T> { }` and `interface Observable<T> extends ObservableReadonly<T> { }`, so 
```ts
const observable = $(1);
const observableReadonly: ObservableReadonly<number> = observable;
```
is okay.

**Comment by fabiospampinato** [comment]
> I use const observableReadonly = useComputed(() => observable); for now.

You should call the observable inside the computed though, otherwise you are just creating a computed that points to an observable (rather than its value) and the computed itself would never change, it's kind of the same as just writing `() => observable`.

> is okay.

I think that's an OK way to do it, making the observable read-only at the type level, though it's important to understand that the observable won't actually be read-only that way for real.
